In [1]:
from transformers import TFBertModel
bert_model_name = 'bert-base-uncased'
bert_model = TFBertModel.from_pretrained(bert_model_name)


/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFBertModel: ['cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.weight', 'cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.bias', 'cls.predictions.bias', 'cls.predictions.transform.dense.bias']
- This IS expected if you are initializing TFBertModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFBertModel were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions w

In [ ]:
from transformers import BertTokenizer
bert_tokenizer = BertTokenizer.from_pretrained(bert_model_name)


tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

In [ ]:
sentence="play football"

tokens = bert_tokenizer.tokenize(sentence)

for token in tokens:
    token_id = bert_tokenizer.convert_tokens_to_ids(token)
    print(f"Token: {token}, Token ID: {token_id}")


Token: play, Token ID: 2377
Token: football, Token ID: 2374


In [ ]:
sentence="play foottball"

tokens = bert_tokenizer.tokenize(sentence)

for token in tokens:
    token_id = bert_tokenizer.convert_tokens_to_ids(token)
    print(f"Token: {token}, Token ID: {token_id}")


Token: play, Token ID: 2377
Token: foot, Token ID: 3329
Token: ##t, Token ID: 2102
Token: ##ball, Token ID: 7384


In [ ]:
sentence = "play football"

tokens_ids_tensor = bert_tokenizer(sentence, return_tensors='tf')
tokens_ids_tensor

{'input_ids': <tf.Tensor: shape=(1, 4), dtype=int32, numpy=array([[ 101, 2377, 2374,  102]], dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(1, 4), dtype=int32, numpy=array([[0, 0, 0, 0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(1, 4), dtype=int32, numpy=array([[1, 1, 1, 1]], dtype=int32)>}

In [ ]:
tokens_ids=tokens_ids_tensor['input_ids']
for i in range(len(tokens_ids)):
    print(f"Tokens: {tokens_ids[i]}")

Tokens: [ 101 2377 2374  102]


In [ ]:
tokens_ids

<tf.Tensor: shape=(1, 4), dtype=int32, numpy=array([[ 101, 2377, 2374,  102]], dtype=int32)>

In [ ]:
tokens_ids.numpy()[0]

array([ 101, 2377, 2374,  102], dtype=int32)

In [ ]:
tokens = bert_tokenizer.convert_ids_to_tokens(tokens_ids[0])
tokens

['[CLS]', 'play', 'football', '[SEP]']

In [ ]:
outputs = bert_model(tokens_ids)
embeddings = outputs.last_hidden_state[0]
embeddings

<tf.Tensor: shape=(4, 768), dtype=float32, numpy=
array([[-0.06533393,  0.17863342, -0.7151851 , ..., -0.3502431 ,
         0.25331253, -0.16033997],
       [ 0.5684662 ,  0.38644454, -0.37973726, ..., -0.04288115,
         0.8225426 , -0.5262483 ],
       [-0.87382674,  0.46802184, -0.45601678, ..., -0.64438367,
        -0.2901885 , -0.08778846],
       [ 0.9062135 ,  0.01561301, -0.34200692, ...,  0.23352203,
        -0.48927236, -0.33302477]], dtype=float32)>

In [ ]:
len(embeddings[1])

768

In [ ]:
embeddings[1]

<tf.Tensor: shape=(768,), dtype=float32, numpy=
array([ 5.68466187e-01,  3.86444539e-01, -3.79737258e-01, -4.53449517e-01,
        2.75026947e-01,  1.52930841e-01,  5.20604610e-01,  2.33973563e-01,
        2.06903890e-01,  1.78228140e-01,  8.34441334e-02, -1.84459031e-01,
       -3.77947271e-01,  4.55421925e-01,  5.15616015e-02, -4.41768378e-01,
        5.03026605e-01,  7.01987624e-01,  2.00024351e-01,  1.17048597e+00,
       -4.69979703e-01,  2.55084634e-01, -1.44906677e-02,  4.87473786e-01,
        4.82248574e-01, -3.72097373e-01,  1.97029173e-01,  7.42826402e-01,
        4.49556261e-02, -1.24112152e-01,  2.77448088e-01,  1.12660684e-01,
        3.78830552e-01,  5.70117235e-01, -5.55280030e-01, -3.46264333e-01,
       -5.13958275e-01,  5.84937096e-01, -4.37671214e-01,  9.46374238e-01,
        7.22997487e-02, -1.76262230e-01, -8.70639458e-02,  4.50080991e-01,
       -2.37382591e-01, -3.04200977e-01,  2.14095891e-01, -4.02155787e-01,
        1.43589169e-01, -1.35590136e-03,  3.46419096

In [ ]:
word = "play"
sentence1 = "I want to play football this morning"
sentence2 = "We are going to the theater to watch a play"

tokens_sentence1 = bert_tokenizer(sentence1, return_tensors='tf')
tokens_sentence2 = bert_tokenizer(sentence2, return_tensors='tf')
tokens_sentence1_ids=tokens_sentence1['input_ids'].numpy()[0]
tokens_sentence2_ids=tokens_sentence2['input_ids'].numpy()[0]
tokens_sentence1_ids,tokens_sentence2_ids

(array([ 101, 1045, 2215, 2000, 2377, 2374, 2023, 2851,  102], dtype=int32),
 array([ 101, 2057, 2024, 2183, 2000, 1996, 4258, 2000, 3422, 1037, 2377,
         102], dtype=int32))

In [ ]:
word_id=bert_tokenizer.convert_tokens_to_ids(word)
word_id

2377

In [ ]:
import numpy as np
word_token_index_sentence1 = np.where(tokens_sentence1_ids == word_id)[0][0]
word_token_index_sentence2 = np.where(tokens_sentence2_ids == word_id)[0][0]
word_token_index_sentence1,word_token_index_sentence2

(4, 10)

In [ ]:
outputs1 = bert_model(tokens_sentence1)
outputs2 = bert_model(tokens_sentence2)

embeddings_sentence1 = outputs1.last_hidden_state.numpy()[0]
embeddings_sentence2 = outputs2.last_hidden_state.numpy()[0]

embedding_word_sentence1 = embeddings_sentence1[word_token_index_sentence1]
embedding_word_sentence2 = embeddings_sentence2[word_token_index_sentence2]

from sklearn.metrics.pairwise import cosine_similarity
similarity_score = cosine_similarity([embedding_word_sentence1], [embedding_word_sentence2])

print("Similarity score:", round(100*similarity_score[0][0],2))

Similarity score: 48.61


In [ ]:
sentence1 = "I want to play football this morning"
sentence2 = "I play tennis with Jack today"
tokens_sentence1 = bert_tokenizer(sentence1, return_tensors='tf')
tokens_sentence2 = bert_tokenizer(sentence2, return_tensors='tf')
tokens_sentence1_ids=tokens_sentence1['input_ids'].numpy()[0]
tokens_sentence2_ids=tokens_sentence2['input_ids'].numpy()[0]
word_id=bert_tokenizer.convert_tokens_to_ids(word)
word_token_index_sentence1 = np.where(tokens_sentence1_ids == word_id)[0][0]
word_token_index_sentence2 = np.where(tokens_sentence2_ids == word_id)[0][0]
word_token_index_sentence1,word_token_index_sentence2
word_token_index_sentence1 = np.where(tokens_sentence1_ids == word_id)[0][0]
word_token_index_sentence2 = np.where(tokens_sentence2_ids == word_id)[0][0]
outputs1 = bert_model(tokens_sentence1)
outputs2 = bert_model(tokens_sentence2)

embeddings_sentence1 = outputs1.last_hidden_state.numpy()[0]
embeddings_sentence2 = outputs2.last_hidden_state.numpy()[0]

embedding_word_sentence1 = embeddings_sentence1[word_token_index_sentence1]
embedding_word_sentence2 = embeddings_sentence2[word_token_index_sentence2]

from sklearn.metrics.pairwise import cosine_similarity
similarity_score = cosine_similarity([embedding_word_sentence1], [embedding_word_sentence2])

print("Similarity score:", round(100*similarity_score[0][0],2))



Similarity score: 77.29


In [ ]:
sentence1 = "I love programming in Python"
sentence2 = "Python is a great programming language"

tokens_sentence1 = bert_tokenizer(sentence1, return_tensors='tf')
tokens_sentence2 = bert_tokenizer(sentence2, return_tensors='tf')

embeddings_sentence1 = bert_model(tokens_sentence1)['last_hidden_state']
embeddings_sentence2 = bert_model(tokens_sentence2)['last_hidden_state']

avg_embedding_sentence1 = np.mean(embeddings_sentence1, axis=1)
avg_embedding_sentence2 = np.mean(embeddings_sentence2, axis=1)

similarity_score = cosine_similarity(avg_embedding_sentence1, avg_embedding_sentence2)

print(f"Cosine similarity between: \n'{sentence1}' and \n'{sentence2}': {round(float(similarity_score), 2)}")


Cosine similarity between: 
'I love programming in Python' and 
'Python is a great programming language': 0.81


<ipython-input-18-5e17e5b97cf3>:20: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  print(f"Cosine similarity between: \n'{sentence1}' and \n'{sentence2}': {round(float(similarity_score), 2)}")


In [ ]:
sentence1 = "I love programming in Python"
sentence2 = "The movie was very bad"

tokens_sentence1 = bert_tokenizer(sentence1, return_tensors='tf')
tokens_sentence2 = bert_tokenizer(sentence2, return_tensors='tf')

embeddings_sentence1 = bert_model(tokens_sentence1)['last_hidden_state']
embeddings_sentence2 = bert_model(tokens_sentence2)['last_hidden_state']

avg_embedding_sentence1 = np.mean(embeddings_sentence1, axis=1)
avg_embedding_sentence2 = np.mean(embeddings_sentence2, axis=1)

similarity_score = cosine_similarity(avg_embedding_sentence1, avg_embedding_sentence2)

print(f"Cosine similarity between: \n'{sentence1}' and \n'{sentence2}': {round(float(similarity_score), 2)}")


Cosine similarity between: 
'I love programming in Python' and 
'The movie was very bad': 0.54


<ipython-input-19-3cf8c6e622c6>:20: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  print(f"Cosine similarity between: \n'{sentence1}' and \n'{sentence2}': {round(float(similarity_score), 2)}")
